/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2017-11-28 22:51:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.Connection;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.Statement");
    _jspx_imports_classes.add("java.sql.DriverManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"utf-8\">\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\n");
      out.write("        <title>Index</title>\n");
      out.write("        <meta name=\"description\" content=\"\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/bootstrap-theme.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/main.css\">\n");
      out.write("        <script src=\"js/vendor/modernizr-2.8.3-respond-1.4.2.min.js\"></script>\n");
      out.write("        <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\n");
      out.write("        <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("       <nav class=\"navbar navbar-light\" style=\"background-color: #46b8da\">\n");
      out.write("           <a href=\"index.jsp\"><img src=\"img/train.png\" width=\"50\" height=\"50\"></a>\n");
      out.write("           Hott'oys\n");
      out.write("           <a href=\"index.jsp\"><img src=\"img/train.png\" width=\"50\" height=\"50\"></a>\n");
      out.write("           \n");
      out.write("           <div class=\"dropdown pull-right\">\n");
      out.write("            <a data-toggle=\"dropdown\"><img src=\"img/crown.png\" width=\"50\" height=\"50\"></a>\n");
      out.write("            <ul class=\"dropdown-menu\">\n");
      out.write("                <div class=\"formadmin\">\n");
      out.write("                <form action=\"Admin\" method=\"Post\">\n");
      out.write("                    <font size=\"4\" color=\"red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mensagem}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</font><br>\n");
      out.write("                    \n");
      out.write("                    <label for=\"adminlogin\">Nome: </label><input type=\"text\" id=\"adminlogin\" name=\"adminlogin\" maxlength=\"30\" placeholder=\"Login\" required name=adminlogin>\n");
      out.write("                    <label for=\"adminlogin\">Senha: </label><input type=\"password\" id=\"adminsenha\" name=\"adminsenha\" maxlength=\"30\" placeholder=\"Senha\" required name=adminsenha><br><br>\n");
      out.write("                    <button class=\"btn-primary\">Entrar</button>\n");
      out.write("                </form>\n");
      out.write("                </div>\n");
      out.write("            </ul>\n");
      out.write("            </div>\n");
      out.write("       </nav>\n");
      out.write("       \n");
      out.write("        <div class=\"container recente\">\n");
      out.write("                <div class=\"col-md-4\">\n");
      out.write("                    <div class=\"list-group\">\n");
      out.write("                        <a href=\"#\" class=\"list-group-item disabled\">Brinquedos</a>\n");
      out.write("                        \n");
 
    String nomecategoria;
    int id;
    
    Class.forName("com.mysql.jdbc.Driver").newInstance();
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/brinquedos",
				"root", "abc123");
    Statement stmt = conn.createStatement();
    ResultSet rs = stmt.executeQuery("select * from Categorias");
    while(rs.next()){
        nomecategoria = rs.getString("NomeCategoria");
        id = rs.getInt("IdCategoria");

      out.write("\n");
      out.write("                    <a href=\"#\" class=\"list-group-item\" id=\"");
      out.print(id);
      out.write("\" onclick=\"Sessão(this)\">");
      out.print(nomecategoria);
      out.write("</a>                   \n");
 }
    
    rs.close();
    stmt.close();
    conn.close();


      out.write("  \n");
      out.write("                                 <a href=\"#\" class=\"list-group-item\" id=\"90\" onclick=\"Sessão(this)\">Todos</a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-8\" id=\"brinquedos\">                   \n");
      out.write("                    \n");
      out.write("                    <!-- Div para mostrar a aba de bonecos -->\n");
      out.write("                    \n");
      out.write("                    <div id=\"bonecos\" style=\"display:block\">\n");
      out.write("                        \n");
      out.write("                        <div class=\"row\">\n");
      out.write("                        <div class=\"col-md-4\">\n");
      out.write("                            <img src=\"img/boneca1.jpg\" width=\"200\" height=\"150\"><br><br>\n");
      out.write("                            Boneca Docinho De Bebe<br>\n");
      out.write("                            R$ 64,89<br>\n");
      out.write("                            <a href=\"brinquedo1.jsp\" class=\"btn-primary\">Saiba mais</a><br>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"col-md-4\">\n");
      out.write("                            <img src=\"img/boneco2.png\" width=\"200\" height=\"150\"><br><br>\n");
      out.write("                            Bonecos Turma Super Mario Bros 6 Peças<br>\n");
      out.write("                            R$ 89,90<br>\n");
      out.write("                            <a href=\"brinquedo2.jsp\" class=\"btn-primary\">Saiba mais</a><br>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"col-md-4\">\n");
      out.write("                            <img src=\"img/boneca3.png\" width=\"200\" height=\"150\"><br><br>\n");
      out.write("                            Boneca Barbie Princesa Penteados Mágicos<br>\n");
      out.write("                            R$ 109,30<br>\n");
      out.write("                            <a href=\"brinquedo3.jsp\" class=\"btn-primary\">Saiba mais</a><br>\n");
      out.write("                        </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <!-- Div para mostrar a aba de carrinhos -->\n");
      out.write("                    \n");
      out.write("                    <div id=\"carrinhos\" style=\"display:block\">\n");
      out.write("                        <div class=\"row\">\n");
      out.write("                        <div class=\"col-md-4\">\n");
      out.write("                            <img src=\"img/carro1.png\" width=\"200\" height=\"150\"><br><br>\n");
      out.write("                            Carro Land Evok Artoys<br>\n");
      out.write("                            R$ 7,99<br>\n");
      out.write("                             <a href=\"brinquedo4.jsp\" class=\"btn-primary\">Saiba mais</a><br>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"col-md-4\">\n");
      out.write("                            <img src=\"img/carro3.png\" width=\"200\" height=\"150\"><br><br>\n");
      out.write("                            Carrinho Pick Up Vision Tuning<br>\n");
      out.write("                            R$ 38,84<br>\n");
      out.write("                             <a href=\"brinquedo5.jsp\" class=\"btn-primary\">Saiba mais</a><br>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"col-md-4\">\n");
      out.write("                            <img src=\"img/carro2.jpg\" width=\"200\" height=\"150\"><br><br>\n");
      out.write("                            Kit com 3 Veículos Carros<br>\n");
      out.write("                            R$ 179,90<br>\n");
      out.write("                             <a href=\"brinquedo6.jsp\" class=\"btn-primary\">Saiba mais</a><br>\n");
      out.write("                        </div>\n");
      out.write("                        </div>    \n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <!-- Div para mostrar a aba de jogos de mesa -->\n");
      out.write("                    \n");
      out.write("                    <div id=\"tabuleiros\" style=\"display:block\">\n");
      out.write("                        <div class=\"row\">\n");
      out.write("                        <div class=\"col-md-4\">\n");
      out.write("                            <img src=\"img/jogo1.png\" width=\"200\" height=\"150\"><br><br>\n");
      out.write("                            Jogo Pie Face!<br>\n");
      out.write("                            R$ 107,70<br>\n");
      out.write("                             <a href=\"brinquedo7.jsp\" class=\"btn-primary\">Saiba mais</a><br>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"col-md-4\">\n");
      out.write("                            <img src=\"img/jogo2.png\" width=\"200\" height=\"150\"><br><br>\n");
      out.write("                            Jogo Pie Face: O Duelo<br>\n");
      out.write("                            R$ 139,99<br>\n");
      out.write("                             <a href=\"brinquedo8.jsp\" class=\"btn-primary\">Saiba mais</a><br>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"col-md-4\">\n");
      out.write("                            <img src=\"img/jogo3.png\" width=\"200\" height=\"150\"><br><br>\n");
      out.write("                            Jogo Super Banco Imobiliário<br>\n");
      out.write("                            R$ 169,90<br>\n");
      out.write("                             <a href=\"brinquedo9.jsp\" class=\"btn-primary\">Saiba mais</a><br>\n");
      out.write("                        </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <!-- Div para mostrar a aba de brinquedos para praia -->\n");
      out.write("                    \n");
      out.write("                    <div id=\"praia\" style=\"display:block\">\n");
      out.write("                        <div class=\"row\">\n");
      out.write("                        <div class=\"col-md-4\">\n");
      out.write("                            <img src=\"img/praia1.png\" width=\"200\" height=\"150\"><br><br>\n");
      out.write("                            Conjunto de Praia<br>\n");
      out.write("                            R$ 29,90<br>\n");
      out.write("                             <a href=\"brinquedo10.jsp\" class=\"btn-primary\">Saiba mais</a><br>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"col-md-4\">\n");
      out.write("                            <img src=\"img/praia2.png\" width=\"200\" height=\"150\"><br><br>\n");
      out.write("                            Brinquedo Vou Pra Praia com 9 peças<br>\n");
      out.write("                            R$ 45,99<br>\n");
      out.write("                             <a href=\"brinquedo11.jsp\" class=\"btn-primary\">Saiba mais</a><br>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"col-md-4\">\n");
      out.write("                            <img src=\"img/praia3.png\" width=\"200\" height=\"150\"><br><br>\n");
      out.write("                            Tenda Praia Homem Aranha<br>\n");
      out.write("                            R$ 45,99<br>\n");
      out.write("                             <a href=\"brinquedo12.jsp\" class=\"btn-primary\">Saiba mais</a><br>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>     \n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("                    <br><br><div class=\"meio1\">\n");
      out.write("            <button type=\"button\" onclick=\"window.location.href='brinqrecentes.jsp'\" class=\"btn-primary\">Produtos recentes</button>\n");
      out.write("            </div>\n");
      out.write("                    \n");
      out.write("        <footer class=\"footer\">\n");
      out.write("            Atura ou Surta\n");
      out.write("        </footer>\n");
      out.write("    \n");
      out.write("                     <script>\n");
      out.write("            function Sessão(obj){\n");
      out.write("                document.getElementById('bonecos').style.display=\"block\";\n");
      out.write("                document.getElementById('carrinhos').style.display=\"block\";\n");
      out.write("                document.getElementById('tabuleiros').style.display=\"block\";\n");
      out.write("                document.getElementById('praia').style.display=\"block\";\n");
      out.write("                \n");
      out.write("                switch(obj.id){                    \n");
      out.write("                    case '1':\n");
      out.write("                    document.getElementById('bonecos').style.display=\"block\";\n");
      out.write("                    document.getElementById('carrinhos').style.display=\"none\";\n");
      out.write("                    document.getElementById('tabuleiros').style.display=\"none\";\n");
      out.write("                    document.getElementById('praia').style.display=\"none\";\n");
      out.write("                    \n");
      out.write("                    break\n");
      out.write("                    \n");
      out.write("                    case '2':\n");
      out.write("                    document.getElementById('bonecos').style.display=\"none\";\n");
      out.write("                    document.getElementById('carrinhos').style.display=\"block\";\n");
      out.write("                    document.getElementById('tabuleiros').style.display=\"none\";\n");
      out.write("                    document.getElementById('praia').style.display=\"none\";\n");
      out.write("                    break\n");
      out.write("                    \n");
      out.write("                    case '3':\n");
      out.write("                    document.getElementById('bonecos').style.display=\"none\";\n");
      out.write("                    document.getElementById('carrinhos').style.display=\"none\";\n");
      out.write("                    document.getElementById('tabuleiros').style.display=\"block\";\n");
      out.write("                    document.getElementById('praia').style.display=\"none\";\n");
      out.write("                    break\n");
      out.write("                    \n");
      out.write("                    case '4':\n");
      out.write("                    document.getElementById('bonecos').style.display=\"none\";\n");
      out.write("                    document.getElementById('carrinhos').style.display=\"none\";\n");
      out.write("                    document.getElementById('tabuleiros').style.display=\"none\";\n");
      out.write("                    document.getElementById('praia').style.display=\"block\";\n");
      out.write("                    break\n");
      out.write("                    \n");
      out.write("                   case '90':\n");
      out.write("                    document.getElementById('bonecos').style.display=\"block\";\n");
      out.write("                    document.getElementById('carrinhos').style.display=\"block\";\n");
      out.write("                    document.getElementById('tabuleiros').style.display=\"block\";\n");
      out.write("                    document.getElementById('praia').style.display=\"block\";\n");
      out.write("                    break\n");
      out.write("                \n");
      out.write("                } \n");
      out.write("            }\n");
      out.write("        </script>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
